server:
  port: 8081

spring:
  application:
    name: myco

  h2:
    console:
      path: /h2-console
      enabled: true

springdoc:
  api-docs:
    path: /swagger
  swagger-ui:
    path: /swagger.html


file:
  upload-dir: uploads/
qr:
  searchUrl: http://localhost:8080/
