spring:
  datasource:
    url: jdbc:h2:file:/data/myco
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      mode: embedded

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB



  web:
    resources:
      static-locations: file:///${file.upload-dir}

file:
  upload-dir: D:/GitProject/uploads/
  access-location: http://localhost:${server.port}/




qr:
  searchUrl: http://localhost:8081/



